backend:
  name: github
  repo: cyntGutiva/demo-veterinaria
  branch: master

media_folder: public/images
public_folder: /images

collections:
  - name: "services"
    label: "Servicios"
    folder: "src/content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Precio", name: "price", widget: "number" }
      - { label: "Ícono", name: "icon", widget: "string", required: false }
      - { label: "Orden", name: "order", widget: "number", default: 0 }
